name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.92.142
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/event-management
            git pull origin main
            npm install
            pm2 restart event-app
